# Generated by Django 4.2.10 on 2024-04-10 12:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id_client", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id_order", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_order", models.DateTimeField(auto_now=True)),
                ("status_order", models.CharField()),
                ("id_transaction", models.CharField()),
                (
                    "id_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airplane_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id_product",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Product Id"
                    ),
                ),
                ("name", models.CharField(verbose_name="Product name")),
                ("description", models.TextField(verbose_name="Product description")),
                ("price", models.FloatField(verbose_name="Product price")),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="Product image"),
                ),
                ("stock", models.IntegerField(verbose_name="Product remaining stock")),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(verbose_name="Quantity of ordered product"),
                ),
                ("price", models.FloatField(verbose_name="Total price of the order")),
                (
                    "id_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airplane_app.order",
                    ),
                ),
                (
                    "id_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airplane_app.product",
                    ),
                ),
            ],
        ),
    ]
