# Generated by Django 4.2.10 on 2024-04-16 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airplane_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
